name: jlab-mrcc
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults
dependencies:
  # mutation-rate-intervals deps
  - python>=3.6
  - scipy=1.1.0
  - numpy=1.12.1
  - mpmath=1.0.0
  - mmh3
   # jupyterlab, notebook utilites
  - pandas
  - seaborn
  - jupyterlab
  - tqdm
# install pkg directly from github
  - pip
  - pip: 
    #- git+https://github.com/KoslickiLab/mutation-rate-ci-calculator@master
    - git+https://github.com/KoslickiLab/mutation-rate-ci-calculator@mahmudur
